server:
  port: 8080
  ssl:
    key-store: C:\Program Files\Java\jdk1.8.0_191\bin\keystore.jks
    key-store-password: gorany
    key-password: gorany
    key-alias: tomcat
    
    trust-store: C:\Program Files\Java\jdk1.8.0_191\bin\keystore.jks
    trust-store-password: gorany
 

spring:    
  datasource:
    url: jdbc:mysql://10.10.10.102:3306/gorany?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true 
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: salem
    password: salem
    
  thymeleaf:
    cache: false
    

logging:
  level:
    org.hibernate: debug
    org.springframework: info
    org.salem: debug
    